import type { Metadata } from "next";

import { AdminLayout } from "@/components/templates";

export const metadata: Metadata = {
  title: {
    template: "Admin Panel | %s",
    default: "Admin Panel",
  },
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return <AdminLayout>{children}</AdminLayout>;
}
